language: ruby
rvm:
- 2.4.0

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild.sh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# Upgrade the SSL otherwise outwards connections will fail
addons:
  apt:
    packages:
      - libssl1.0.0

sudo: false # route your build to the container-based infrastructure for a faster build
